title: SL Notebook
url: "https://juan-castrillon.github.io"
#baseurl: "/self-learning-notes"

remote_theme: pmarsceill/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
logo: "/img/waaa.png"

search_enabled: true
