title: SL Notebook
url: https://juan-castrillon.github.io/self-learning-notes/
baseurl: "self-learning-notes/"

remote_theme: pmarsceill/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

search_enabled: true
